name: 'Action 2'

description: 'test action 2'

inputs:
  tpm2tss_branch:
    required: false
  tpm2tools_branch:
    required: false

runs:
  using: composite
  steps:
    - name: etcetc
      env:
        TPM2TOOLS_BRANCH: ${{ inputs.tpm2tools_branch }}
        TPM2TSS_BRANCH: ${{ inputs.tpm2tss_branch }}
      run: |
        echo "TPM Tools Branch: $TPM2TOOLS_BRANCH"
        echo "TPM Tss Branch: $TPM2TSS_BRANCH"
      shell: bash
